name: Deploy on EC2 CI

on:
  push:
    branches:
      - deploy-fxmodel-docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh  
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        # checks if no folder than clones , if exists than pulls latest
        # shell scripting, fi is used to mark the end of an if statement
        # In shell scripting, EOF (End of File) is commonly used to denote the end of a block of text that is being redirected as input to a command
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu
          if [ ! -d "fxmodelci" ]; then
            git clone https://github.com/Adeesh-bode/FXModel.git fxmodelci
          else
            cd fxmodelci
            git pull origin main
          fi
          cd /home/ubuntu/fxmodelci
          docker-compose down
          docker-compose up -d --build
          EOF
