name: try2

# defines when the workflow will be triggered
on:
  push:
    branches:
      - deploy-fxmodel-docker  # branch to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # step-1 :the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
      # Set up SSH access to the EC2 instance
      - name: Set up SSH # Secure Shell - cryptographic network protocol allows secure communtn btw 2 computers over an unsecured network. # remote system execute command 
        # create dir if doesnt exists , put secrets , change permission ( 600 -R/W owner only ) , add the host to "Known Host" to avoid manual ssh host vertification
        run: |
          mkdir -p ~/.ssh  
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Transfer files to EC2
        # Secure copyprotocol - SCP uses SSH to transfer data- files are encrypted during transit. 
        run: |
          scp -r ${{ github.workspace }}/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu

      # connect ec2 and deploy
      - name: Deploy on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/fxmodel
          docker-compose down
          git pull origin main
          docker-compose up -d --build
          EOF
